Feature/create search response fragment
AnDrOiD73dd/cinema-finder pull request #32
Opened 2018-11-05 18:00 UTC by z0lk1n

2018-11-05 20:11 UTC, AnDrOiD73dd requested changes

2018-11-05 20:11 UTC, AnDrOiD73dd commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/RecyclerViewAdapter.java
> +public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ViewHolder> {
Плохое название класса. Нужно что-то более осмысленное, чтобы было понятно для чего этот адаптер используется.

2018-11-05 20:11 UTC, AnDrOiD73dd commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/RecyclerViewAdapter.java
> +    }
Мы договорились делать презентер для адаптера. Ну или как минимум лучше вместо этих 6 строк вызывать `viewHolder.bind(i)`

2018-11-05 20:11 UTC, AnDrOiD73dd commented on presentation/src/main/res/drawable/ic_broken_image.xml
> +        android:fillColor="#FF000000"
Цвет можно вынести в ресурсы. Один и тот же используется в нескольких местах и изменяться они буду тоже скорее всего вместе.

2018-11-05 20:11 UTC, AnDrOiD73dd commented on presentation/src/main/res/values/strings.xml
> +    <string name="time_unit">мин.</string>
Этот файл strings.xml находится в values и, видимо, тут должны быть только англоязычные ресурсы

2018-11-05 20:14 UTC, z0lk1n commented on presentation/src/main/res/values/strings.xml
> +    <string name="time_unit">мин.</string>
это рудимент, исправил

2018-11-05 20:22 UTC, z0lk1n commented on presentation/src/main/res/drawable/ic_broken_image.xml
> +        android:fillColor="#FF000000"
исправил

2018-11-05 20:28 UTC, z0lk1n commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/RecyclerViewAdapter.java
> +public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ViewHolder> {
готово

2018-11-05 21:37 UTC, z0lk1n commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/RecyclerViewAdapter.java
> +    }
сделал презентер

2018-11-06 07:19 UTC, AnDrOiD73dd approved these changes

2018-11-06 07:19 UTC, merged