moved private methods
AnDrOiD73dd/cinema-finder pull request #57
Opened 2018-11-09 15:32 UTC by z0lk1n

2018-11-09 22:18 UTC, AnDrOiD73dd requested changes

2018-11-09 22:18 UTC, AnDrOiD73dd commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/AppActivity.java
> +        setContentView(R.layout.activity_main);
`setContentView(R.layout.activity_main);` должно быть перед всем остальным. Или есть какая-то причина по которой  `setStatusBarColor `должен быть перед `setContentView`? У меня все работает если изменить порядок.

2018-11-09 22:18 UTC, AnDrOiD73dd commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/AppActivity.java
> +        setContentView(R.layout.activity_main);
Аналогично касается и super.onCreate 
```
super.onCreate(savedInstanceState);
App.getApp().getAppComponent().inject(this);
```
Сначала вызывается super.onCreate, затем все остальное.

2018-11-09 22:18 UTC, AnDrOiD73dd commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/screens/main/home/HomeFragment.java
> +    private void init() {
Один и тот же метод в нескольких фрагментах отличающийся названием ресурса. Стоит задуматься о DRY.

2018-11-10 07:09 UTC, z0lk1n commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/AppActivity.java
> +        setContentView(R.layout.activity_main);
сделал

2018-11-10 07:11 UTC, z0lk1n commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/screens/main/home/HomeFragment.java
> +    private void init() {
Из-за того, что это child fragments, у каждого должны вызываться эти методы при отображении фрагмента

2018-11-10 09:14 UTC, z0lk1n commented on presentation/src/main/java/com/ateam/zuml/cinemafinder/ui/screens/main/home/HomeFragment.java
> +    private void init() {
сделал

2018-11-10 10:00 UTC, AnDrOiD73dd approved these changes

2018-11-10 10:00 UTC, merged